# Global configuration
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.
  # scrape_timeout is set to the global default (10s).

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's the Prometheus server itself.
scrape_configs:
  # Scrape configuration for your server application.
  - job_name: 'infra'
    static_configs:
      - targets: ['127.0.0.1:9100']
        labels:
          env: 'development'
  - job_name: 'server'
    static_configs:
      - targets: ['127.0.0.1:8081']
        labels:
          env: 'development'

# Optionally add more scrape configurations for other services here.

